build:
	go build -o bin/labeler ./cmd/...

install:
	chmod +x bin/labeler
	sudo cp bin/labeler /usr/local/bin

run:
	go run labeler.go

compile:
	echo "Compiling for every OS and Platform"
	GOOS=darwin GOARCH=amd64 go build -o bin/labeler-darwin-amd64 ./cmd/...
	GOOS=linux GOARCH=arm go build -o bin/labeler-linux-arm ./cmd/...
	GOOS=darwin GOARCH=arm64 go build -o bin/labeler-darwin-arm64 ./cmd/...
	GOOS=linux GOARCH=arm64 go build -o bin/labeler-linux-arm64 ./cmd/...
	GOOS=linux GOARCH=amd64 go build -o bin/labeler-linux-amd64 ./cmd/...
	GOOS=linux GOARCH=386 go build -o bin/labeler-linux-386 ./cmd/...
	GOOS=windows GOARCH=386 go build -o bin/labeler-windows-386 ./cmd/...
	GOOS=windows GOARCH=amd64 go build -o bin/labeler-windows-386 ./cmd/...
	GOOS=freebsd GOARCH=386 go build -o bin/labeler-freebsd-386 ./cmd/...
	GOOS=linux GOARCH=ppc64 go build -o bin/labeler-linux-ppc64 ./cmd/...
	GOOS=linux GOARCH=ppc64le go build -o bin/labeler-linux-ppc64le ./cmd/...
	GOOS=linux GOARCH=s390x go build -o bin/labeler-linux-s390x ./cmd/...
	GOOS=linux GOARCH=arm GOARM=7 go build -o bin/labeler-linux-armv7 ./cmd/...

all: build install