build:
	go build -o bin/labeler ./cmd/...

install:
	chmod +x bin/labeler
	sudo cp bin/labeler /usr/local/bin

run:
	go run labeler.go

compile:
	echo "Compiling for every OS and Platform"
	GOOS=linux GOARCH=arm go build -o bin/labeler-linux-arm ./cmd/...
	GOOS=linux GOARCH=arm64 go build -o bin/labeler-linux-arm64 ./cmd/...
	GOOS=linux GOARCH=386 go build -o bin/labeler-linux-386 ./cmd/...
	GOOS=windows GOARCH=386 go build -o bin/labeler-windows-386 ./cmd/...
	GOOS=freebsd GOARCH=386 go build -o bin/labeler-freebsd-386 ./cmd/...

all: build install